// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ControlOutlined: typeof import('@ant-design/icons-vue')['ControlOutlined']
    ExportOutlined: typeof import('@ant-design/icons-vue')['ExportOutlined']
    FileOutlined: typeof import('@ant-design/icons-vue')['FileOutlined']
    FolderOpenOutlined: typeof import('@ant-design/icons-vue')['FolderOpenOutlined']
    FundViewOutlined: typeof import('@ant-design/icons-vue')['FundViewOutlined']
    ImportOutlined: typeof import('@ant-design/icons-vue')['ImportOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    SaveOutlined: typeof import('@ant-design/icons-vue')['SaveOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
    ZoomInOutlined: typeof import('@ant-design/icons-vue')['ZoomInOutlined']
    ZoomOutOutlined: typeof import('@ant-design/icons-vue')['ZoomOutOutlined']
  }
}

export {}
