// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    PropertiesEditor: typeof import('./components/PropertiesEditor.vue')['default']
    TestPropertiesEditor: typeof import('./components/test/TestPropertiesEditor.vue')['default']
  }
}

export {}
